### ISSUE TITLE
[bug] "Cannot convert undefined or null to object" 

### ISSUE THREAD

**Issue by 15800436469try** [ms-iot/vscode-ros#151] opened 2019-11-11 05:55 UTC
when I start debug,it shows a wrong information  "Cannot convert undefined or null to object" ,but my steps is right

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "ROS: Launch",
            "request": "launch",
            "target": "/home/luochao/catkin_ws/src/beginner_tutorials/launch/turtleminic.launch",
            "type": "ros"
        }
    ]
}

**Comment by rcabg** [comment] 2019-11-28 07:38
Same problem here. So far unable to do a roslaunch debug since always appears that message.

Ubuntu 16.04
vscode: 1.40.1
ROS extension: 0.6.2
ROS Kinetic

**Comment by Hyeokreal** [comment] 2020-07-14 04:17
Same problem here.

**Comment by matthias-mayr** [comment] 2020-07-16 14:47
I had the same issue with codium 1.46.1-1592564058 on Ubuntu 18.04. I upgraded `codium` to the latest version 1.47.1-1594810499. I was not able to find this extension in the marketplace after the upgrade anymore, so I downloaded the `vsix` file from the website and installed it manually. 
But now this error message is gone.

**Comment by ooeygui** [comment] 2021-11-06 22:37
Closing, I cannot reproduce this. If you are able to get a stack trace, or a pointer to a repo or which can reproduce this, please reopen

**Closed by ooeygui** 2021-11-06 22:37 UTC
Labels: bug
