### ISSUE TITLE
why does it export so mang things when I run a launch file？

### ISSUE THREAD

**Issue by ku-zhen** [ms-iot/vscode-ros#874] opened 2023-02-11 06:03 UTC
hello, every time I run a launch file by this extension, it will export so many things. This will take two seconds, but calling in the terminal does nothing. They don't seem to be doing anything here, how do I remove it?

ubuntu: 20.04 (ros noetic)

![_20230211135543](https://user-images.githubusercontent.com/61906420/218243050-2c7daf3e-1226-4482-87fd-5bdf54d4737c.jpg)

**Comment by ravijo** [comment] 2023-02-11 14:32
I have never seen such a scenario so far. So I need more information. Therefore, can you please explain the steps you followed in detail?

**Comment by ku-zhen** [comment] 2023-02-12 06:32
STEPS:
1. open a catkin workspace with vscode; 
2. use the shortcut key "ctrl+shift+B" to start **catkin_make: build**.   
3. After the build is complete, use the **ROS: Run a ROS launch file(roslaunch)** command. 
4. After selecting the package and launch file , the console will export some things like above before launch the node.

**Comment by ravijo** [comment] 2023-02-13 01:31
@ku-zhen 

Thanks a lot. I noticed the same behavior in my setup. 

By the way, I never use the command palette (Ctrl+Shift+P) inside vscode to run a launch file. Instead, you can type the command directly in terminal inside vscode and that way we don't export those variables. 

Cheers!

**Comment by polyhobbyist** [comment] 2023-03-03 19:59
Launch from roslaunch creates a new terminal; which inherits the vscode launch environment.

**Comment by ooeygui** [comment] 2023-03-27 21:31
Closing as this is by design due to environment inheritance.

**Closed by ooeygui** 2023-03-27 21:31 UTC
Labels: bug
